version: "3.6"

services:
  web:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    network_mode: host
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - PIXIV_COOKIE=${PIXIV_COOKIE}
      - API_HOST=${API_HOST}
      - API_NO_HTTPS=${API_NO_HTTPS}
      - IMAGE_HOST=${IMAGE_HOST}
      - IMAGE_NO_HTTPS=${IMAGE_NO_HTTPS}
      - NSFW_ENDPOINT=${NSFW_ENDPOINT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DB_SYNC_TOKEN=${DB_SYNC_TOKEN}
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  mariadb-volume:
