apiVersion: v1
kind: Service
metadata:
  name: genshin-picbed
  labels:
    app: genshin-picbed
spec:
  ports:
    - port: 3000
  selector:
    app: genshin-picbed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genshin-picbed
  labels:
    app: genshin-picbed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: genshin-picbed
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: genshin-picbed
    spec:
      containers:
      - image: museaqours/genshin-picbed:latest
        name: genshin-picbed
        ports:
        - containerPort: 3000
          name: genshin-picbed
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 3
        resources:
          requests:
            memory: "150Mi"
          limits:
            memory: "150Mi"
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: genshin-picbed-secret
              key: MONGODB_URL
        - name: PIXIV_COOKIE
          valueFrom:
            secretKeyRef:
              name: genshin-picbed-secret
              key: PIXIV_COOKIE
              optional: true
        - name: IMAGE_HOST
          valueFrom:
            configMapKeyRef:
              name: genshin-picbed-config
              key: IMAGE_HOST
        - name: NSFW_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: genshin-picbed-secret
              key: NSFW_ENDPOINT
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: genshin-picbed-secret
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: genshin-picbed-secret
              key: GOOGLE_CLIENT_SECRET
        - name: GOOGLE_REDIRECT_URL
          valueFrom:
            secretKeyRef:
              name: genshin-picbed-secret
              key: GOOGLE_REDIRECT_URL
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: genshin-picbed-secret
              key: GOOGLE_API_KEY
        - name: DB_SYNC_TOKEN
          valueFrom:
            secretKeyRef:
              name: genshin-picbed-secret
              key: DB_SYNC_TOKEN
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: genshin-picbed-config
data:
  IMAGE_HOST: "img.minamiktr.com"
